apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-kube-taint-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-kube-taint-controller
  template:
    metadata:
      labels:
        app: carbon-kube-taint-controller
    spec:
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["taintcontroller"]
